<?php

namespace Database\Seeders;

use App\Models\WishlistItem;
use Illuminate\Database\Seeder;

class WishlistItemSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'title' => 'Surgical Gauze Rolls (Pack of 4)',
                'category' => 'MEDICAL',
                'price' => '₹165',
                'image_url' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=surgical+gauze+roll',
                'amazon_url' => 'https://www.amazon.in/s?k=surgical+gauze+roll',
                'target_quantity' => 100,
                'received_quantity' => 45,
                'is_urgent' => true,
                'is_active' => true,
                'order_priority' => 1,
            ],
            [
                'title' => 'Surgical Cotton Roll 1 KG (100% Pure Absorbent)',
                'category' => 'MEDICAL',
                'price' => '₹289',
                'image_url' => 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=surgical+cotton+roll+1kg',
                'amazon_url' => 'https://www.amazon.in/s?k=surgical+cotton+roll+1kg',
                'target_quantity' => 50,
                'received_quantity' => 28,
                'is_urgent' => true,
                'is_active' => true,
                'order_priority' => 2,
            ],
            [
                'title' => 'Self-Adhesive Elastic Bandage Wrap (6 Pack)',
                'category' => 'MEDICAL',
                'price' => '₹289',
                'image_url' => 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=self+adhesive+bandage+wrap',
                'amazon_url' => 'https://www.amazon.in/s?k=self+adhesive+bandage+wrap',
                'target_quantity' => 60,
                'received_quantity' => 30,
                'is_urgent' => false,
                'is_active' => true,
                'order_priority' => 3,
            ],
            [
                'title' => 'Sterile Wound Dressings & Gauze Pads',
                'category' => 'MEDICAL',
                'price' => '₹185',
                'image_url' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=sterile+wound+dressing',
                'amazon_url' => 'https://www.amazon.in/s?k=sterile+wound+dressing',
                'target_quantity' => 40,
                'received_quantity' => 15,
                'is_urgent' => true,
                'is_active' => true,
                'order_priority' => 4,
            ],
            [
                'title' => 'IV Infusion Sets & Saline Tubes (Pack of 10)',
                'category' => 'MEDICAL',
                'price' => '₹355',
                'image_url' => 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=iv+infusion+set',
                'amazon_url' => 'https://www.amazon.in/s?k=iv+infusion+set',
                'target_quantity' => 30,
                'received_quantity' => 12,
                'is_urgent' => false,
                'is_active' => true,
                'order_priority' => 5,
            ],
            [
                'title' => 'Antiseptic Disinfectant Floor Cleaner 5 Litres',
                'category' => 'HYGIENE',
                'price' => '₹550',
                'image_url' => 'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=disinfectant+floor+cleaner+5l',
                'amazon_url' => 'https://www.amazon.in/s?k=disinfectant+floor+cleaner+5l',
                'target_quantity' => 40,
                'received_quantity' => 22,
                'is_urgent' => false,
                'is_active' => true,
                'order_priority' => 6,
            ],
            [
                'title' => 'Pure Aloe Vera Soothing Gel 500ml',
                'category' => 'MEDICAL',
                'price' => '₹350',
                'image_url' => 'https://images.unsplash.com/photo-1567928257400-f1454b1d701d?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=aloe+vera+gel+500ml',
                'amazon_url' => 'https://www.amazon.in/s?k=aloe+vera+gel+500ml',
                'target_quantity' => 25,
                'received_quantity' => 10,
                'is_urgent' => false,
                'is_active' => true,
                'order_priority' => 7,
            ],
            [
                'title' => 'Anti-Flea & Tick Medicated Pet Shampoo 1L',
                'category' => 'HYGIENE',
                'price' => '₹1,299',
                'image_url' => 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=anti+flea+tick+shampoo+dog',
                'amazon_url' => 'https://www.amazon.in/s?k=anti+flea+tick+shampoo+dog',
                'target_quantity' => 20,
                'received_quantity' => 8,
                'is_urgent' => false,
                'is_active' => true,
                'order_priority' => 8,
            ],
            [
                'title' => 'NexGard Flea & Tick Chewable Tablets',
                'category' => 'MEDICAL',
                'price' => '₹2,099',
                'image_url' => 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=nexgard+chewable+tablets+dog',
                'amazon_url' => 'https://www.amazon.in/s?k=nexgard+chewable+tablets+dog',
                'target_quantity' => 30,
                'received_quantity' => 14,
                'is_urgent' => true,
                'is_active' => true,
                'order_priority' => 9,
            ],
            [
                'title' => 'Vet-Pro Sensitive Adult Dry Dog Kibble 10kg',
                'category' => 'FOOD',
                'price' => '₹4,599',
                'image_url' => 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=vet+pro+sensitive+dog+food+10kg',
                'amazon_url' => 'https://www.amazon.in/s?k=vet+pro+sensitive+dog+food+10kg',
                'target_quantity' => 25,
                'received_quantity' => 18,
                'is_urgent' => true,
                'is_active' => true,
                'order_priority' => 10,
            ],
            [
                'title' => 'Drools Adult Chicken & Eggs Dry Kibble 20kg',
                'category' => 'FOOD',
                'price' => '₹2,999',
                'image_url' => 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=drools+adult+dog+food+20kg',
                'amazon_url' => 'https://www.amazon.in/s?k=drools+adult+dog+food+20kg',
                'target_quantity' => 50,
                'received_quantity' => 35,
                'is_urgent' => false,
                'is_active' => true,
                'order_priority' => 11,
            ],
            [
                'title' => 'Nitrile Examination Gloves Powder-Free (Box of 100)',
                'category' => 'HYGIENE',
                'price' => '₹499',
                'image_url' => 'https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=nitrile+gloves+box+of+100',
                'amazon_url' => 'https://www.amazon.in/s?k=nitrile+gloves+box+of+100',
                'target_quantity' => 40,
                'received_quantity' => 26,
                'is_urgent' => false,
                'is_active' => true,
                'order_priority' => 12,
            ],
            [
                'title' => 'Latex Surgical Examination Gloves (Box of 100)',
                'category' => 'HYGIENE',
                'price' => '₹420',
                'image_url' => 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=latex+examination+gloves+box+of+100',
                'amazon_url' => 'https://www.amazon.in/s?k=latex+examination+gloves+box+of+100',
                'target_quantity' => 30,
                'received_quantity' => 19,
                'is_urgent' => false,
                'is_active' => true,
                'order_priority' => 13,
            ],
            [
                'title' => 'Pet Grooming & Dryer Warmer 2000W',
                'category' => 'EQUIPMENT',
                'price' => '₹987',
                'image_url' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500&auto=format&fit=crop&q=80',
                'flipkart_url' => 'https://www.flipkart.com/search?q=pet+grooming+dryer',
                'amazon_url' => 'https://www.amazon.in/s?k=pet+grooming+dryer',
                'target_quantity' => 10,
                'received_quantity' => 4,
                'is_urgent' => false,
                'is_active' => true,
                'order_priority' => 14,
            ],
        ];

        foreach ($products as $prod) {
            WishlistItem::updateOrCreate(
                ['title' => $prod['title']],
                $prod
            );
        }
    }
}
